name: deploy notification
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - test
      
jobs:
  generate-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.head.ref == 'refs/heads/changeset-release/test'
    steps:
      - run: echo "${{ github.event.pull_request.body }}"
